# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 841)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 610))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Droplet = QtWidgets.QWidget()
        self.tab_Droplet.setObjectName("tab_Droplet")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_Droplet)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_DropletSubtab = QtWidgets.QTabWidget(self.tab_Droplet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_DropletSubtab.sizePolicy().hasHeightForWidth())
        self.tab_DropletSubtab.setSizePolicy(sizePolicy)
        self.tab_DropletSubtab.setObjectName("tab_DropletSubtab")
        self.tab_singlePulse = QtWidgets.QWidget()
        self.tab_singlePulse.setObjectName("tab_singlePulse")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_singlePulse)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_singlepulse = QtWidgets.QGridLayout()
        self.gridLayout_singlepulse.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_singlepulse.setObjectName("gridLayout_singlepulse")
        self.spinBoxDrops_sgl = QtWidgets.QSpinBox(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxDrops_sgl.sizePolicy().hasHeightForWidth())
        self.spinBoxDrops_sgl.setSizePolicy(sizePolicy)
        self.spinBoxDrops_sgl.setKeyboardTracking(False)
        self.spinBoxDrops_sgl.setMinimum(1)
        self.spinBoxDrops_sgl.setMaximum(32000)
        self.spinBoxDrops_sgl.setProperty("value", 1000)
        self.spinBoxDrops_sgl.setObjectName("spinBoxDrops_sgl")
        self.gridLayout_singlepulse.addWidget(self.spinBoxDrops_sgl, 7, 1, 1, 1)
        self.label_sgltrigger = QtWidgets.QLabel(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sgltrigger.sizePolicy().hasHeightForWidth())
        self.label_sgltrigger.setSizePolicy(sizePolicy)
        self.label_sgltrigger.setObjectName("label_sgltrigger")
        self.gridLayout_singlepulse.addWidget(self.label_sgltrigger, 5, 0, 1, 1)
        self.radioButton_sglreleaseCont = QtWidgets.QRadioButton(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_sglreleaseCont.sizePolicy().hasHeightForWidth())
        self.radioButton_sglreleaseCont.setSizePolicy(sizePolicy)
        self.radioButton_sglreleaseCont.setAutoExclusive(True)
        self.radioButton_sglreleaseCont.setObjectName("radioButton_sglreleaseCont")
        self.buttonGroup_singleRelease = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_singleRelease.setObjectName("buttonGroup_singleRelease")
        self.buttonGroup_singleRelease.addButton(self.radioButton_sglreleaseCont)
        self.gridLayout_singlepulse.addWidget(self.radioButton_sglreleaseCont, 4, 2, 1, 1)
        self.radioButton_sgltriggerMDG = QtWidgets.QRadioButton(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_sgltriggerMDG.sizePolicy().hasHeightForWidth())
        self.radioButton_sgltriggerMDG.setSizePolicy(sizePolicy)
        self.radioButton_sgltriggerMDG.setAutoExclusive(True)
        self.radioButton_sgltriggerMDG.setObjectName("radioButton_sgltriggerMDG")
        self.buttonGroup_singleTrigger = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_singleTrigger.setObjectName("buttonGroup_singleTrigger")
        self.buttonGroup_singleTrigger.addButton(self.radioButton_sgltriggerMDG)
        self.gridLayout_singlepulse.addWidget(self.radioButton_sgltriggerMDG, 5, 2, 1, 1)
        self.label_sglstrobedelay = QtWidgets.QLabel(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sglstrobedelay.sizePolicy().hasHeightForWidth())
        self.label_sglstrobedelay.setSizePolicy(sizePolicy)
        self.label_sglstrobedelay.setObjectName("label_sglstrobedelay")
        self.gridLayout_singlepulse.addWidget(self.label_sglstrobedelay, 8, 0, 1, 1)
        self.spinBoxFreq_sgl = QtWidgets.QSpinBox(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFreq_sgl.sizePolicy().hasHeightForWidth())
        self.spinBoxFreq_sgl.setSizePolicy(sizePolicy)
        self.spinBoxFreq_sgl.setKeyboardTracking(False)
        self.spinBoxFreq_sgl.setMinimum(1)
        self.spinBoxFreq_sgl.setMaximum(6000)
        self.spinBoxFreq_sgl.setProperty("value", 50)
        self.spinBoxFreq_sgl.setObjectName("spinBoxFreq_sgl")
        self.gridLayout_singlepulse.addWidget(self.spinBoxFreq_sgl, 6, 1, 1, 1)
        self.doubleSpinBox_sglPWidth = QtWidgets.QDoubleSpinBox(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_sglPWidth.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_sglPWidth.setSizePolicy(sizePolicy)
        self.doubleSpinBox_sglPWidth.setKeyboardTracking(False)
        self.doubleSpinBox_sglPWidth.setDecimals(1)
        self.doubleSpinBox_sglPWidth.setMinimum(1.0)
        self.doubleSpinBox_sglPWidth.setMaximum(200.0)
        self.doubleSpinBox_sglPWidth.setObjectName("doubleSpinBox_sglPWidth")
        self.gridLayout_singlepulse.addWidget(self.doubleSpinBox_sglPWidth, 2, 1, 1, 1)
        self.label_sglreleasemode = QtWidgets.QLabel(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sglreleasemode.sizePolicy().hasHeightForWidth())
        self.label_sglreleasemode.setSizePolicy(sizePolicy)
        self.label_sglreleasemode.setObjectName("label_sglreleasemode")
        self.gridLayout_singlepulse.addWidget(self.label_sglreleasemode, 4, 0, 1, 1)
        self.label_sglPWidth = QtWidgets.QLabel(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sglPWidth.sizePolicy().hasHeightForWidth())
        self.label_sglPWidth.setSizePolicy(sizePolicy)
        self.label_sglPWidth.setObjectName("label_sglPWidth")
        self.gridLayout_singlepulse.addWidget(self.label_sglPWidth, 2, 0, 1, 1)
        self.radioButton_sglreleaseBurst = QtWidgets.QRadioButton(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_sglreleaseBurst.sizePolicy().hasHeightForWidth())
        self.radioButton_sglreleaseBurst.setSizePolicy(sizePolicy)
        self.radioButton_sglreleaseBurst.setChecked(True)
        self.radioButton_sglreleaseBurst.setObjectName("radioButton_sglreleaseBurst")
        self.buttonGroup_singleRelease.addButton(self.radioButton_sglreleaseBurst)
        self.gridLayout_singlepulse.addWidget(self.radioButton_sglreleaseBurst, 4, 1, 1, 1)
        self.label_sglFreq = QtWidgets.QLabel(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sglFreq.sizePolicy().hasHeightForWidth())
        self.label_sglFreq.setSizePolicy(sizePolicy)
        self.label_sglFreq.setObjectName("label_sglFreq")
        self.gridLayout_singlepulse.addWidget(self.label_sglFreq, 6, 0, 1, 1)
        self.spinBoxStrobedelay_sgl = QtWidgets.QSpinBox(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxStrobedelay_sgl.sizePolicy().hasHeightForWidth())
        self.spinBoxStrobedelay_sgl.setSizePolicy(sizePolicy)
        self.spinBoxStrobedelay_sgl.setKeyboardTracking(False)
        self.spinBoxStrobedelay_sgl.setMaximum(1000)
        self.spinBoxStrobedelay_sgl.setProperty("value", 200)
        self.spinBoxStrobedelay_sgl.setObjectName("spinBoxStrobedelay_sgl")
        self.gridLayout_singlepulse.addWidget(self.spinBoxStrobedelay_sgl, 8, 1, 1, 1)
        self.label_sgldrops = QtWidgets.QLabel(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sgldrops.sizePolicy().hasHeightForWidth())
        self.label_sgldrops.setSizePolicy(sizePolicy)
        self.label_sgldrops.setObjectName("label_sgldrops")
        self.gridLayout_singlepulse.addWidget(self.label_sgldrops, 7, 0, 1, 1)
        self.label_sglVoltage = QtWidgets.QLabel(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sglVoltage.sizePolicy().hasHeightForWidth())
        self.label_sglVoltage.setSizePolicy(sizePolicy)
        self.label_sglVoltage.setScaledContents(True)
        self.label_sglVoltage.setIndent(0)
        self.label_sglVoltage.setObjectName("label_sglVoltage")
        self.gridLayout_singlepulse.addWidget(self.label_sglVoltage, 1, 0, 1, 1)
        self.radioButton_sgltriggerTOF = QtWidgets.QRadioButton(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_sgltriggerTOF.sizePolicy().hasHeightForWidth())
        self.radioButton_sgltriggerTOF.setSizePolicy(sizePolicy)
        self.radioButton_sgltriggerTOF.setCheckable(True)
        self.radioButton_sgltriggerTOF.setChecked(True)
        self.radioButton_sgltriggerTOF.setAutoExclusive(True)
        self.radioButton_sgltriggerTOF.setObjectName("radioButton_sgltriggerTOF")
        self.buttonGroup_singleTrigger.addButton(self.radioButton_sgltriggerTOF)
        self.gridLayout_singlepulse.addWidget(self.radioButton_sgltriggerTOF, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_singlepulse.addItem(spacerItem, 4, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_singlepulse.addItem(spacerItem1, 0, 0, 1, 1)
        self.spinBox_sglV = QtWidgets.QSpinBox(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_sglV.sizePolicy().hasHeightForWidth())
        self.spinBox_sglV.setSizePolicy(sizePolicy)
        self.spinBox_sglV.setKeyboardTracking(False)
        self.spinBox_sglV.setObjectName("spinBox_sglV")
        self.gridLayout_singlepulse.addWidget(self.spinBox_sglV, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_singlepulse.addItem(spacerItem2, 3, 0, 1, 1)
        self.label_sglStrobeWidth = QtWidgets.QLabel(self.tab_singlePulse)
        self.label_sglStrobeWidth.setObjectName("label_sglStrobeWidth")
        self.gridLayout_singlepulse.addWidget(self.label_sglStrobeWidth, 9, 0, 1, 1)
        self.doubleSpinBox_sglStrobeWidth = QtWidgets.QDoubleSpinBox(self.tab_singlePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_sglStrobeWidth.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_sglStrobeWidth.setSizePolicy(sizePolicy)
        self.doubleSpinBox_sglStrobeWidth.setKeyboardTracking(False)
        self.doubleSpinBox_sglStrobeWidth.setMinimum(0.01)
        self.doubleSpinBox_sglStrobeWidth.setMaximum(9.99)
        self.doubleSpinBox_sglStrobeWidth.setSingleStep(0.5)
        self.doubleSpinBox_sglStrobeWidth.setProperty("value", 2.0)
        self.doubleSpinBox_sglStrobeWidth.setObjectName("doubleSpinBox_sglStrobeWidth")
        self.gridLayout_singlepulse.addWidget(self.doubleSpinBox_sglStrobeWidth, 9, 1, 1, 1)
        self.gridLayout_singlepulse.setColumnMinimumWidth(0, 180)
        self.gridLayout_singlepulse.setColumnMinimumWidth(1, 70)
        self.gridLayout_singlepulse.setColumnMinimumWidth(2, 70)
        self.gridLayout_singlepulse.setColumnMinimumWidth(3, 70)
        self.gridLayout_singlepulse.setRowMinimumHeight(0, 40)
        self.gridLayout_singlepulse.setRowMinimumHeight(1, 40)
        self.gridLayout_singlepulse.setRowMinimumHeight(2, 40)
        self.gridLayout_singlepulse.setRowMinimumHeight(3, 40)
        self.gridLayout_singlepulse.setRowMinimumHeight(4, 40)
        self.gridLayout_singlepulse.setRowMinimumHeight(5, 40)
        self.gridLayout_singlepulse.setRowMinimumHeight(6, 40)
        self.gridLayout_singlepulse.setRowMinimumHeight(7, 40)
        self.gridLayout_singlepulse.setRowMinimumHeight(8, 40)
        self.gridLayout_singlepulse.setRowMinimumHeight(9, 40)
        self.verticalLayout_5.addLayout(self.gridLayout_singlepulse)
        self.pushButton_sgldrops = QtWidgets.QPushButton(self.tab_singlePulse)
        self.pushButton_sgldrops.setCheckable(True)
        self.pushButton_sgldrops.setChecked(False)
        self.pushButton_sgldrops.setFlat(False)
        self.pushButton_sgldrops.setObjectName("pushButton_sgldrops")
        self.buttonGroup_startDrops = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_startDrops.setObjectName("buttonGroup_startDrops")
        self.buttonGroup_startDrops.setExclusive(False)
        self.buttonGroup_startDrops.addButton(self.pushButton_sgldrops)
        self.verticalLayout_5.addWidget(self.pushButton_sgldrops)
        self.pushButton_sglcamera = QtWidgets.QPushButton(self.tab_singlePulse)
        self.pushButton_sglcamera.setCheckable(True)
        self.pushButton_sglcamera.setObjectName("pushButton_sglcamera")
        self.buttonGroup_startCamera = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_startCamera.setObjectName("buttonGroup_startCamera")
        self.buttonGroup_startCamera.setExclusive(False)
        self.buttonGroup_startCamera.addButton(self.pushButton_sglcamera)
        self.verticalLayout_5.addWidget(self.pushButton_sglcamera)
        self.tab_DropletSubtab.addTab(self.tab_singlePulse, "")
        self.tab_triplePulse = QtWidgets.QWidget()
        self.tab_triplePulse.setObjectName("tab_triplePulse")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_triplePulse)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_triplepulse = QtWidgets.QGridLayout()
        self.gridLayout_triplepulse.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_triplepulse.setObjectName("gridLayout_triplepulse")
        self.label_releasemode = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_releasemode.sizePolicy().hasHeightForWidth())
        self.label_releasemode.setSizePolicy(sizePolicy)
        self.label_releasemode.setObjectName("label_releasemode")
        self.gridLayout_triplepulse.addWidget(self.label_releasemode, 5, 0, 1, 1)
        self.radioButton_triggerMDG = QtWidgets.QRadioButton(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_triggerMDG.sizePolicy().hasHeightForWidth())
        self.radioButton_triggerMDG.setSizePolicy(sizePolicy)
        self.radioButton_triggerMDG.setAutoExclusive(True)
        self.radioButton_triggerMDG.setObjectName("radioButton_triggerMDG")
        self.buttonGroup_tripleTrigger = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_tripleTrigger.setObjectName("buttonGroup_tripleTrigger")
        self.buttonGroup_tripleTrigger.addButton(self.radioButton_triggerMDG)
        self.gridLayout_triplepulse.addWidget(self.radioButton_triggerMDG, 6, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_triplepulse.addItem(spacerItem3, 4, 0, 1, 1)
        self.spinBoxV2 = QtWidgets.QSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxV2.sizePolicy().hasHeightForWidth())
        self.spinBoxV2.setSizePolicy(sizePolicy)
        self.spinBoxV2.setKeyboardTracking(False)
        self.spinBoxV2.setMinimum(-250)
        self.spinBoxV2.setMaximum(250)
        self.spinBoxV2.setObjectName("spinBoxV2")
        self.gridLayout_triplepulse.addWidget(self.spinBoxV2, 1, 2, 1, 1)
        self.doubleSpinBoxPDelay1 = QtWidgets.QDoubleSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPDelay1.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPDelay1.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPDelay1.setKeyboardTracking(False)
        self.doubleSpinBoxPDelay1.setDecimals(1)
        self.doubleSpinBoxPDelay1.setMinimum(0.3)
        self.doubleSpinBoxPDelay1.setProperty("value", 1.0)
        self.doubleSpinBoxPDelay1.setObjectName("doubleSpinBoxPDelay1")
        self.gridLayout_triplepulse.addWidget(self.doubleSpinBoxPDelay1, 3, 1, 1, 1)
        self.doubleSpinBoxPDelay3 = QtWidgets.QDoubleSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPDelay3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPDelay3.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPDelay3.setKeyboardTracking(False)
        self.doubleSpinBoxPDelay3.setDecimals(1)
        self.doubleSpinBoxPDelay3.setMinimum(0.3)
        self.doubleSpinBoxPDelay3.setProperty("value", 1.0)
        self.doubleSpinBoxPDelay3.setObjectName("doubleSpinBoxPDelay3")
        self.gridLayout_triplepulse.addWidget(self.doubleSpinBoxPDelay3, 3, 3, 1, 1)
        self.doubleSpinBoxPDelay2 = QtWidgets.QDoubleSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPDelay2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPDelay2.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPDelay2.setKeyboardTracking(False)
        self.doubleSpinBoxPDelay2.setDecimals(1)
        self.doubleSpinBoxPDelay2.setMinimum(0.3)
        self.doubleSpinBoxPDelay2.setProperty("value", 1.0)
        self.doubleSpinBoxPDelay2.setObjectName("doubleSpinBoxPDelay2")
        self.gridLayout_triplepulse.addWidget(self.doubleSpinBoxPDelay2, 3, 2, 1, 1)
        self.spinBoxDrops = QtWidgets.QSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxDrops.sizePolicy().hasHeightForWidth())
        self.spinBoxDrops.setSizePolicy(sizePolicy)
        self.spinBoxDrops.setKeyboardTracking(False)
        self.spinBoxDrops.setMinimum(1)
        self.spinBoxDrops.setMaximum(32000)
        self.spinBoxDrops.setProperty("value", 1000)
        self.spinBoxDrops.setObjectName("spinBoxDrops")
        self.gridLayout_triplepulse.addWidget(self.spinBoxDrops, 8, 1, 1, 1)
        self.spinBoxV1 = QtWidgets.QSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxV1.sizePolicy().hasHeightForWidth())
        self.spinBoxV1.setSizePolicy(sizePolicy)
        self.spinBoxV1.setKeyboardTracking(False)
        self.spinBoxV1.setMinimum(-250)
        self.spinBoxV1.setMaximum(250)
        self.spinBoxV1.setObjectName("spinBoxV1")
        self.gridLayout_triplepulse.addWidget(self.spinBoxV1, 1, 1, 1, 1)
        self.label_Voltage = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Voltage.sizePolicy().hasHeightForWidth())
        self.label_Voltage.setSizePolicy(sizePolicy)
        self.label_Voltage.setScaledContents(True)
        self.label_Voltage.setIndent(0)
        self.label_Voltage.setObjectName("label_Voltage")
        self.gridLayout_triplepulse.addWidget(self.label_Voltage, 1, 0, 1, 1)
        self.label_strobedelay = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_strobedelay.sizePolicy().hasHeightForWidth())
        self.label_strobedelay.setSizePolicy(sizePolicy)
        self.label_strobedelay.setObjectName("label_strobedelay")
        self.gridLayout_triplepulse.addWidget(self.label_strobedelay, 9, 0, 1, 1)
        self.radioButton_triggerTOF = QtWidgets.QRadioButton(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_triggerTOF.sizePolicy().hasHeightForWidth())
        self.radioButton_triggerTOF.setSizePolicy(sizePolicy)
        self.radioButton_triggerTOF.setCheckable(True)
        self.radioButton_triggerTOF.setChecked(True)
        self.radioButton_triggerTOF.setAutoExclusive(True)
        self.radioButton_triggerTOF.setObjectName("radioButton_triggerTOF")
        self.buttonGroup_tripleTrigger.addButton(self.radioButton_triggerTOF)
        self.gridLayout_triplepulse.addWidget(self.radioButton_triggerTOF, 6, 1, 1, 1)
        self.spinBoxStrobedelay = QtWidgets.QSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxStrobedelay.sizePolicy().hasHeightForWidth())
        self.spinBoxStrobedelay.setSizePolicy(sizePolicy)
        self.spinBoxStrobedelay.setKeyboardTracking(False)
        self.spinBoxStrobedelay.setMaximum(1000)
        self.spinBoxStrobedelay.setProperty("value", 200)
        self.spinBoxStrobedelay.setObjectName("spinBoxStrobedelay")
        self.gridLayout_triplepulse.addWidget(self.spinBoxStrobedelay, 9, 1, 1, 1)
        self.label_drops = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_drops.sizePolicy().hasHeightForWidth())
        self.label_drops.setSizePolicy(sizePolicy)
        self.label_drops.setObjectName("label_drops")
        self.gridLayout_triplepulse.addWidget(self.label_drops, 8, 0, 1, 1)
        self.label_PDelay = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_PDelay.sizePolicy().hasHeightForWidth())
        self.label_PDelay.setSizePolicy(sizePolicy)
        self.label_PDelay.setTextFormat(QtCore.Qt.AutoText)
        self.label_PDelay.setWordWrap(False)
        self.label_PDelay.setObjectName("label_PDelay")
        self.gridLayout_triplepulse.addWidget(self.label_PDelay, 3, 0, 1, 1)
        self.label_Freq = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Freq.sizePolicy().hasHeightForWidth())
        self.label_Freq.setSizePolicy(sizePolicy)
        self.label_Freq.setObjectName("label_Freq")
        self.gridLayout_triplepulse.addWidget(self.label_Freq, 7, 0, 1, 1)
        self.doubleSpinBoxPWidth1 = QtWidgets.QDoubleSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPWidth1.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPWidth1.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPWidth1.setKeyboardTracking(False)
        self.doubleSpinBoxPWidth1.setDecimals(1)
        self.doubleSpinBoxPWidth1.setMinimum(1.0)
        self.doubleSpinBoxPWidth1.setMaximum(200.0)
        self.doubleSpinBoxPWidth1.setObjectName("doubleSpinBoxPWidth1")
        self.gridLayout_triplepulse.addWidget(self.doubleSpinBoxPWidth1, 2, 1, 1, 1)
        self.label_PWidth = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_PWidth.sizePolicy().hasHeightForWidth())
        self.label_PWidth.setSizePolicy(sizePolicy)
        self.label_PWidth.setObjectName("label_PWidth")
        self.gridLayout_triplepulse.addWidget(self.label_PWidth, 2, 0, 1, 1)
        self.spinBoxV3 = QtWidgets.QSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxV3.sizePolicy().hasHeightForWidth())
        self.spinBoxV3.setSizePolicy(sizePolicy)
        self.spinBoxV3.setKeyboardTracking(False)
        self.spinBoxV3.setMinimum(-250)
        self.spinBoxV3.setMaximum(250)
        self.spinBoxV3.setObjectName("spinBoxV3")
        self.gridLayout_triplepulse.addWidget(self.spinBoxV3, 1, 3, 1, 1)
        self.doubleSpinBoxPWidth3 = QtWidgets.QDoubleSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPWidth3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPWidth3.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPWidth3.setKeyboardTracking(False)
        self.doubleSpinBoxPWidth3.setDecimals(1)
        self.doubleSpinBoxPWidth3.setMinimum(1.0)
        self.doubleSpinBoxPWidth3.setMaximum(200.0)
        self.doubleSpinBoxPWidth3.setObjectName("doubleSpinBoxPWidth3")
        self.gridLayout_triplepulse.addWidget(self.doubleSpinBoxPWidth3, 2, 3, 1, 1)
        self.radioButton_releaseCont = QtWidgets.QRadioButton(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_releaseCont.sizePolicy().hasHeightForWidth())
        self.radioButton_releaseCont.setSizePolicy(sizePolicy)
        self.radioButton_releaseCont.setAutoExclusive(True)
        self.radioButton_releaseCont.setObjectName("radioButton_releaseCont")
        self.buttonGroup_tripleRelease = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_tripleRelease.setObjectName("buttonGroup_tripleRelease")
        self.buttonGroup_tripleRelease.addButton(self.radioButton_releaseCont)
        self.gridLayout_triplepulse.addWidget(self.radioButton_releaseCont, 5, 2, 1, 1)
        self.doubleSpinBoxPWidth2 = QtWidgets.QDoubleSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxPWidth2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxPWidth2.setSizePolicy(sizePolicy)
        self.doubleSpinBoxPWidth2.setKeyboardTracking(False)
        self.doubleSpinBoxPWidth2.setDecimals(1)
        self.doubleSpinBoxPWidth2.setMinimum(1.0)
        self.doubleSpinBoxPWidth2.setMaximum(200.0)
        self.doubleSpinBoxPWidth2.setObjectName("doubleSpinBoxPWidth2")
        self.gridLayout_triplepulse.addWidget(self.doubleSpinBoxPWidth2, 2, 2, 1, 1)
        self.label_P3 = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_P3.sizePolicy().hasHeightForWidth())
        self.label_P3.setSizePolicy(sizePolicy)
        self.label_P3.setObjectName("label_P3")
        self.gridLayout_triplepulse.addWidget(self.label_P3, 0, 3, 1, 1)
        self.label_P2 = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_P2.sizePolicy().hasHeightForWidth())
        self.label_P2.setSizePolicy(sizePolicy)
        self.label_P2.setObjectName("label_P2")
        self.gridLayout_triplepulse.addWidget(self.label_P2, 0, 2, 1, 1)
        self.radioButton_releaseBurst = QtWidgets.QRadioButton(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_releaseBurst.sizePolicy().hasHeightForWidth())
        self.radioButton_releaseBurst.setSizePolicy(sizePolicy)
        self.radioButton_releaseBurst.setChecked(True)
        self.radioButton_releaseBurst.setObjectName("radioButton_releaseBurst")
        self.buttonGroup_tripleRelease.addButton(self.radioButton_releaseBurst)
        self.gridLayout_triplepulse.addWidget(self.radioButton_releaseBurst, 5, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_triplepulse.addItem(spacerItem4, 0, 0, 1, 1)
        self.label_P1 = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_P1.sizePolicy().hasHeightForWidth())
        self.label_P1.setSizePolicy(sizePolicy)
        self.label_P1.setObjectName("label_P1")
        self.gridLayout_triplepulse.addWidget(self.label_P1, 0, 1, 1, 1)
        self.spinBoxFreq = QtWidgets.QSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFreq.sizePolicy().hasHeightForWidth())
        self.spinBoxFreq.setSizePolicy(sizePolicy)
        self.spinBoxFreq.setKeyboardTracking(False)
        self.spinBoxFreq.setMinimum(1)
        self.spinBoxFreq.setMaximum(6000)
        self.spinBoxFreq.setProperty("value", 50)
        self.spinBoxFreq.setObjectName("spinBoxFreq")
        self.gridLayout_triplepulse.addWidget(self.spinBoxFreq, 7, 1, 1, 1)
        self.label_trigger = QtWidgets.QLabel(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_trigger.sizePolicy().hasHeightForWidth())
        self.label_trigger.setSizePolicy(sizePolicy)
        self.label_trigger.setObjectName("label_trigger")
        self.gridLayout_triplepulse.addWidget(self.label_trigger, 6, 0, 1, 1)
        self.label_strobewidth = QtWidgets.QLabel(self.tab_triplePulse)
        self.label_strobewidth.setObjectName("label_strobewidth")
        self.gridLayout_triplepulse.addWidget(self.label_strobewidth, 10, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_triplePulse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setKeyboardTracking(False)
        self.doubleSpinBox.setMinimum(0.01)
        self.doubleSpinBox.setMaximum(9.99)
        self.doubleSpinBox.setSingleStep(0.5)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_triplepulse.addWidget(self.doubleSpinBox, 10, 1, 1, 1)
        self.gridLayout_triplepulse.setColumnMinimumWidth(0, 180)
        self.gridLayout_triplepulse.setColumnMinimumWidth(1, 70)
        self.gridLayout_triplepulse.setColumnMinimumWidth(2, 70)
        self.gridLayout_triplepulse.setColumnMinimumWidth(3, 70)
        self.gridLayout_triplepulse.setRowMinimumHeight(0, 40)
        self.gridLayout_triplepulse.setRowMinimumHeight(1, 40)
        self.gridLayout_triplepulse.setRowMinimumHeight(2, 40)
        self.gridLayout_triplepulse.setRowMinimumHeight(3, 40)
        self.gridLayout_triplepulse.setRowMinimumHeight(4, 40)
        self.gridLayout_triplepulse.setRowMinimumHeight(5, 40)
        self.gridLayout_triplepulse.setRowMinimumHeight(6, 40)
        self.gridLayout_triplepulse.setRowMinimumHeight(7, 40)
        self.gridLayout_triplepulse.setRowMinimumHeight(8, 40)
        self.gridLayout_triplepulse.setRowMinimumHeight(9, 40)
        self.gridLayout_triplepulse.setRowMinimumHeight(10, 40)
        self.verticalLayout_4.addLayout(self.gridLayout_triplepulse)
        self.pushButton_drops = QtWidgets.QPushButton(self.tab_triplePulse)
        self.pushButton_drops.setCheckable(True)
        self.pushButton_drops.setChecked(False)
        self.pushButton_drops.setFlat(False)
        self.pushButton_drops.setObjectName("pushButton_drops")
        self.buttonGroup_startDrops.addButton(self.pushButton_drops)
        self.verticalLayout_4.addWidget(self.pushButton_drops)
        self.pushButton_camera = QtWidgets.QPushButton(self.tab_triplePulse)
        self.pushButton_camera.setCheckable(True)
        self.pushButton_camera.setObjectName("pushButton_camera")
        self.buttonGroup_startCamera.addButton(self.pushButton_camera)
        self.verticalLayout_4.addWidget(self.pushButton_camera)
        self.tab_DropletSubtab.addTab(self.tab_triplePulse, "")
        self.verticalLayout.addWidget(self.tab_DropletSubtab)
        self.tabWidget.addTab(self.tab_Droplet, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.videoFeed = QtWidgets.QWidget()
        self.videoFeed.setObjectName("videoFeed")
        self.ImgWidget = QtWidgets.QWidget(self.videoFeed)
        self.ImgWidget.setGeometry(QtCore.QRect(10, 10, 461, 501))
        self.ImgWidget.setObjectName("ImgWidget")
        self.startButton = QtWidgets.QPushButton(self.videoFeed)
        self.startButton.setGeometry(QtCore.QRect(10, 520, 181, 32))
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.videoFeed)
        self.stopButton.setGeometry(QtCore.QRect(282, 520, 181, 32))
        self.stopButton.setObjectName("stopButton")
        self.tabWidget.addTab(self.videoFeed, "")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tabWidget)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Settings = QtWidgets.QAction(MainWindow)
        self.actionLoad_Settings.setObjectName("actionLoad_Settings")
        self.actionSave_Settings = QtWidgets.QAction(MainWindow)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.actionSave_Settings_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Settings_As.setObjectName("actionSave_Settings_As")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionLoad_Settings)
        self.menuFile.addAction(self.actionSave_Settings)
        self.menuFile.addAction(self.actionSave_Settings_As)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tab_DropletSubtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_sgltrigger.setText(_translate("MainWindow", "Trigger:"))
        self.radioButton_sglreleaseCont.setText(_translate("MainWindow", "Cont."))
        self.radioButton_sgltriggerMDG.setText(_translate("MainWindow", "MDG"))
        self.label_sglstrobedelay.setText(_translate("MainWindow", "Strobe Delay:"))
        self.label_sglreleasemode.setText(_translate("MainWindow", "Release Mode:"))
        self.label_sglPWidth.setText(_translate("MainWindow", "Pulse Width (us):"))
        self.radioButton_sglreleaseBurst.setText(_translate("MainWindow", "Burst"))
        self.label_sglFreq.setText(_translate("MainWindow", "Frequency (Hz):"))
        self.label_sgldrops.setText(_translate("MainWindow", "Drops:"))
        self.label_sglVoltage.setText(_translate("MainWindow", "Voltage (V):"))
        self.radioButton_sgltriggerTOF.setText(_translate("MainWindow", "TOF"))
        self.label_sglStrobeWidth.setText(_translate("MainWindow", "Strobe Width:"))
        self.pushButton_sgldrops.setText(_translate("MainWindow", "Start Droplets"))
        self.pushButton_sglcamera.setText(_translate("MainWindow", "Start Camera"))
        self.tab_DropletSubtab.setTabText(self.tab_DropletSubtab.indexOf(self.tab_singlePulse), _translate("MainWindow", "Single Pulse"))
        self.label_releasemode.setText(_translate("MainWindow", "Release Mode:"))
        self.radioButton_triggerMDG.setText(_translate("MainWindow", "MDG"))
        self.label_Voltage.setText(_translate("MainWindow", "Voltage (V):"))
        self.label_strobedelay.setText(_translate("MainWindow", "Strobe Delay:"))
        self.radioButton_triggerTOF.setText(_translate("MainWindow", "TOF"))
        self.label_drops.setText(_translate("MainWindow", "Drops:"))
        self.label_PDelay.setText(_translate("MainWindow", "Pulse Delay (us):"))
        self.label_Freq.setText(_translate("MainWindow", "Frequency (Hz):"))
        self.label_PWidth.setText(_translate("MainWindow", "Pulse Width (us):"))
        self.radioButton_releaseCont.setText(_translate("MainWindow", "Cont."))
        self.label_P3.setText(_translate("MainWindow", "Pulse 3"))
        self.label_P2.setText(_translate("MainWindow", "Pulse 2"))
        self.radioButton_releaseBurst.setText(_translate("MainWindow", "Burst"))
        self.label_P1.setText(_translate("MainWindow", "Pulse 1"))
        self.label_trigger.setText(_translate("MainWindow", "Trigger:"))
        self.label_strobewidth.setText(_translate("MainWindow", "Strobe Width:"))
        self.pushButton_drops.setText(_translate("MainWindow", "Start Droplets"))
        self.pushButton_camera.setText(_translate("MainWindow", "Start Camera"))
        self.tab_DropletSubtab.setTabText(self.tab_DropletSubtab.indexOf(self.tab_triplePulse), _translate("MainWindow", "Triple Pulse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Droplet), _translate("MainWindow", "Droplet Generation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Pressure Control"))
        self.startButton.setText(_translate("MainWindow", "Start Capture"))
        self.stopButton.setText(_translate("MainWindow", "Stop Capture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.videoFeed), _translate("MainWindow", "Page"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Settings.setText(_translate("MainWindow", "Load Settings..."))
        self.actionLoad_Settings.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_Settings.setText(_translate("MainWindow", "Save Settings"))
        self.actionSave_Settings.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_Settings_As.setText(_translate("MainWindow", "Save Settings As..."))
        self.actionSave_Settings_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

